openapi: 3.0.3
info:
  title: Chat API
  version: 1.0.0

paths:
  /signup:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'    

  /messages:
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageInput'
      responses:
        '201':
          description: Sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

    get:
      summary: Get messages with a user
      parameters:
        - name: receiver_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

components:
  schemas:
    UserInput:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string
          
    SignupResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name

    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

    LoginRequest:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    Message:
      type: object
      required:
        - id
        - sender_id
        - receiver_id
        - text
        - timestamp
      properties:
        id:
          type: integer
        sender_id:
          type: integer
        receiver_id:
          type: integer
        text:
          type: string
        timestamp:
          type: string
          format: date-time

    MessageInput:
      type: object
      required:
        - receiver_id
        - text
      properties:
        receiver_id:
          type: integer
        text:
          type: string