version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: air -c .air.toml
    environment:
    - DB_DSN=host=db user=user password=password dbname=chat_app_db port=5432 sslmode=disable

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chat_app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - chat_app_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  chat_app_db_data:
  pgadmin-data:
